Mysql:
  Addr: "localhost:3306"
  Username: "root"
  Password: "password"
  Database: "ytdemo"

Redis:
  Addr: "localhost:6379"

Transcode:
  TranscodeCount: 2
  FFmpegPath: "/usr/bin/ffmpeg"
  TranscodeCommandLine: "-i %s -c:v libx264 -crf 18 -c:a aac -b:a 128k -ac 2 -f mp4 %s"